spring.application.name=SMH

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never